"use client";

import { useCallback, useEffect, useState } from "react";
import { ThreatFeedSection } from "@/components/threat-feed/ThreatFeedSection";
import { getFeedItems, getFeedSummary, refreshFeed, type FeedItem, type FeedRegion, type FeedSummary } from "@/lib/api/threatFeed";

const regions: FeedRegion[] = ["global", "malaysia", "southeast_asia"];
export default function ThreatFeedPage() {
  const [items, setItems] = useState<Record<FeedRegion, FeedItem[]>>({ global: [], malaysia: [], southeast_asia: [] });
  const [summary, setSummary] = useState<FeedSummary | null>(null);
  const [query, setQuery] = useState(""); const [topic, setTopic] = useState(""); const [hours, setHours] = useState("168");
  const [status, setStatus] = useState("Loading threat feed…"); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setStatus("Loading threat feed…"); try { const [nextSummary, ...lists] = await Promise.all([getFeedSummary(), ...regions.map((region) => getFeedItems({ region, query, topic, hours: Number(hours), page_size: 5 }))]); setSummary(nextSummary); setItems({ global: lists[0].items, malaysia: lists[1].items, southeast_asia: lists[2].items }); setStatus(""); } catch { setStatus("The feed is temporarily unavailable. Try again shortly."); } }, [query, topic, hours]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  async function refresh() { setBusy(true); try { const result = await refreshFeed(); setStatus(result.status === "cooldown" ? `Refresh is cooling down. Existing reports are still available.` : `${result.items_added} new items collected.`); await load(); } catch { setStatus("Refresh could not be started. Existing reports are unchanged."); } finally { setBusy(false); } }
  return <main className="min-h-screen px-4 py-10"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-sky-400">Source-attributed intelligence</p><h1 className="mt-2 text-3xl font-semibold">Threat Feed</h1><p className="mt-2 max-w-2xl text-sm text-zinc-500">Cybersecurity reporting and official advisories, routed by regional relevance. Source-reported entities remain unverified until investigated.</p></div><button disabled={busy} onClick={() => void refresh()} className="rounded-lg border border-sky-500/30 px-4 py-2 text-sm text-sky-300 hover:bg-sky-500/10 disabled:opacity-50">{busy ? "Refreshing…" : "Refresh feed"}</button></header>
  <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-xs text-zinc-500">New in 24 hours</p><p className="mt-1 text-2xl font-semibold">{summary ? Object.values(summary.regions).reduce((sum, value) => sum + value.recent, 0) : "—"}</p></div><div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-xs text-zinc-500">Source-reported entities</p><p className="mt-1 text-2xl font-semibold">{summary?.new_iocs ?? "—"}</p></div><div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-xs text-zinc-500">Last refresh</p><p className="mt-2 text-sm text-zinc-200">{summary?.last_refreshed_at ? new Date(summary.last_refreshed_at).toLocaleString() : "Not refreshed yet"}</p></div></section>
  <section className="grid gap-3 rounded-2xl border border-zinc-800 bg-zinc-900 p-4 md:grid-cols-[1fr_180px_160px]"><input aria-label="Search threat feed" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles, summaries, sources…" className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm outline-none focus:border-sky-500"/><select aria-label="Topic" value={topic} onChange={(event) => setTopic(event.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">All topics</option>{["advisory","vulnerability","active_exploitation","phishing","ransomware","malware","breach","supply_chain","threat_actor","scam","research"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><select aria-label="Time range" value={hours} onChange={(event) => setHours(event.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select></section>
  {status && <p role="status" className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-400">{status}</p>}
  {regions.map((region) => <ThreatFeedSection key={region} region={region} items={items[region]} total={summary?.regions[region].total ?? items[region].length}/>)}</div></main>;
}
