"use client";
import Link from "next/link";
import { FORMATS, resetPreferences, useExperiencePreferences, writePreferences } from "@/lib/experiencePreferences";
import { DataLocation } from "@/components/ui/DataLocation";
import { useToast } from "@/components/ui/ToastProvider";
export function ExperienceSettings() {
  const p = useExperiencePreferences(); const { notify } = useToast();
  const control = "rounded border border-zinc-700 bg-zinc-950 p-2 text-sm";
  return <><section id="experience" className="space-y-4 rounded-xl border border-zinc-800 p-5"><h2>Experience</h2><DataLocation kind="Browser-local" detail="No queries, identities, or credentials are saved as preferences." />
    <div className="flex flex-wrap gap-3"><label>Default scan <select className={control} value={p.scanMode} onChange={(e) => writePreferences({ scanMode: e.target.value as typeof p.scanMode })}><option value="fast">Fast</option><option value="standard">Standard</option><option value="full">Full</option></select></label><label>Rule view <select className={control} value={p.view} onChange={(e) => writePreferences({ view: e.target.value as typeof p.view })}><option value="compact">Compact</option><option value="card">Cards</option></select></label><label>Page size <select className={control} value={p.pageSize} onChange={(e) => writePreferences({ pageSize: Number(e.target.value) })}>{[10, 20, 50].map((n) => <option key={n}>{n}</option>)}</select></label></div>
    <fieldset><legend>Preferred rule formats (none selected means all)</legend><div className="mt-2 flex flex-wrap gap-3">{FORMATS.map((format) => <label key={format} className="text-xs"><input type="checkbox" checked={p.formats.includes(format)} onChange={(e) => writePreferences({ formats: e.target.checked ? [...p.formats, format] : p.formats.filter((f) => f !== format) })} /> {format}</label>)}</div></fieldset>
    <fieldset><legend>Start these sections collapsed</legend>{["assessment", "providers", "detections"].map((section) => <label key={section} className="mr-3 text-xs"><input type="checkbox" checked={p.collapsed.includes(section)} onChange={(e) => writePreferences({ collapsed: e.target.checked ? [...p.collapsed, section] : p.collapsed.filter((s) => s !== section) })} /> {section}</label>)}</fieldset>
    <button className={control} onClick={() => { resetPreferences(); notify("Preferences reset; saved records and local histories were not deleted."); }}>Reset Preferences</button></section>
    <section id="data-locations" className="space-y-3 rounded-xl border border-zinc-800 p-5"><h2>Where your data lives</h2><p className="text-sm text-zinc-400">Search and PoC results are temporary unless explicitly saved. Investigation caches expire according to their displayed metadata. Saved investigations and Cases use the configured storage backend and are included in personal backups.</p><p className="text-sm text-zinc-400">Batch recovery is browser-local for 24 hours. Email history is browser-local for 90 days; password checks are never retained. Bookmarks and preferences remain until cleared. Public feed records and browser-local data are excluded from personal backups.</p><div className="flex flex-wrap gap-3 text-sky-300"><Link href="/settings?focus=backup">Backup / restore</Link><Link href="/identity">Clear identity history</Link><Link href="/threat-feed?view=saved">Clear feed bookmarks</Link><a href="#experience">Reset preferences</a></div><p className="text-xs text-zinc-500">Each clear control affects only its own data. No combined clear-everything operation.</p></section></>;
}
