import type { InvestigationResponse, InvestigationSummary } from "@/lib/api";
import { severityLabel, confidenceBandLabel } from "@/lib/investigation";
import { DataLocation } from "@/components/ui/DataLocation";
export function ResultOverview({ data, summary, saved = false, scope = "result" }: { data?: InvestigationResponse | null; summary: InvestigationSummary; saved?: boolean; scope?: string }) {
  const providers = [...(data?.threat_intelligence.providers ?? []), ...(data?.knowledge?.providers ?? [])];
  const failed = providers.filter((p) => ["error", "timeout", "rate_limited", "unauthorized", "partial"].includes(p.status));
  return <section aria-label="Result overview" className="space-y-3 rounded-xl border border-zinc-800 bg-zinc-900 p-5 text-sm">
    <div className="flex flex-wrap justify-between gap-2"><h2 className="font-medium text-white">At a glance · {summary.entity_value}</h2><DataLocation kind={saved ? "Saved to database" : "Temporary"} /></div>
    <p className="text-zinc-300">{severityLabel(summary.posture)} posture · {confidenceBandLabel(summary.overall_confidence.band)} confidence ({summary.overall_confidence.score})</p>
    {!data && <p className="text-amber-300">Summary-only record: provider coverage and complete snapshot details are unavailable.</p>}
    {data && <><p className="text-xs text-zinc-400">Supporting coverage: {providers.filter((p) => ["ok", "partial"].includes(p.status)).map((p) => p.provider_display_name ?? p.provider).join(", ") || "No successful provider evidence"}</p><p className="text-xs text-zinc-400">{providers.filter((p) => ["not_found", "unsupported"].includes(p.status)).length} sources returned no data or do not support this entity. Missing evidence is not proof of safety.</p>{failed.length > 0 && <p className="text-amber-300">Partial coverage: {failed.map((p) => `${p.provider}: ${p.status}`).join(", ")}. Available findings remain usable.</p>}{(data.threat_intelligence.agreement?.conflicted || summary.overall_confidence.contested) && <p className="text-amber-300">Conflicting evidence: inspect the supporting and contradicting findings before acting.</p>}<p className="text-xs text-zinc-500">{data.cache?.status === "hit" ? `Cached result, ${data.cache.age_seconds ?? 0}s old` : "Retrieved provider result"}{data.cache?.expires_at ? ` · Cache expires ${data.cache.expires_at}` : ""}</p></>}
    <div className="grid gap-3 sm:grid-cols-2"><div><h3 className="text-zinc-300">Key findings</h3><ul className="text-zinc-400">{summary.findings.slice(0, 3).map((f) => <li key={f.id}><a className="underline focus-visible:outline" href={`#${scope}-findings`}>{f.title}</a></li>)}</ul>{!summary.findings.length && <p className="text-zinc-500">No findings in this assessment.</p>}</div><div><h3 className="text-zinc-300">Suggested next steps</h3><ul className="text-zinc-400">{summary.recommendations.slice(0, 3).map((r, i) => <li key={i}><a className="underline" href={`#${scope}-recommendations`}>{r.action}</a></li>)}</ul>{!summary.recommendations.length && <p className="text-zinc-500">Review source coverage; no specific recommendations were produced.</p>}</div></div>
  </section>;
}
