import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { DEFAULT_PREFERENCES, PREFERENCES_KEY, readPreferences, resetPreferences, writePreferences } from "./experiencePreferences";
beforeEach(() => { const entries = new Map<string, string>(); vi.stubGlobal("localStorage", { getItem: (key: string) => entries.get(key) ?? null, setItem: (key: string, value: string) => entries.set(key, value), removeItem: (key: string) => entries.delete(key) }); vi.stubGlobal("window", { dispatchEvent: vi.fn() }); });
afterEach(() => vi.unstubAllGlobals());
it("writes only the harmless preference allowlist", () => { writePreferences({ scanMode: "full", password: "secret", query: "private@example.test" } as never); const saved = localStorage.getItem(PREFERENCES_KEY)!; expect(saved).not.toContain("secret"); expect(saved).not.toContain("private@example"); expect(readPreferences().scanMode).toBe("full"); });
it("defaults and recovers malformed storage", () => { expect(readPreferences()).toEqual(DEFAULT_PREFERENCES); localStorage.setItem(PREFERENCES_KEY, "bad"); expect(readPreferences()).toEqual(DEFAULT_PREFERENCES); });
it("validates fields and excludes sensitive input from the returned projection", () => { localStorage.setItem(PREFERENCES_KEY, JSON.stringify({ version: 1, value: { scanMode: "bad", pageSize: 999, formats: ["sigma", "sigma", "evil"], password: "secret", collapsed: ["query", "providers"] } })); expect(readPreferences()).toEqual({ scanMode: "standard", view: "compact", pageSize: 20, formats: ["sigma"], collapsed: ["providers"] }); });
it("reset affects only preferences", () => { localStorage.setItem("other-history", "keep"); writePreferences({ scanMode: "fast" }); expect(readPreferences().scanMode).toBe("fast"); resetPreferences(); expect(readPreferences()).toEqual(DEFAULT_PREFERENCES); expect(localStorage.getItem("other-history")).toBe("keep"); });
it("handles blocked storage", () => { vi.stubGlobal("localStorage", { getItem: () => { throw Error(); }, setItem: () => { throw Error(); } }); expect(readPreferences()).toEqual(DEFAULT_PREFERENCES); expect(() => writePreferences({ view: "card" })).not.toThrow(); });
